bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
    path('apply-discount/', views.apply_discount, name='apply_discount'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap
from .sitemaps import (
    StaticViewSitemap,
    BlogSitemap,
    ProductSitemap,
    CategorySitemap,
    SubCategorySitemap
)

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'products': ProductSitemap,
    'categories': CategorySitemap,
    'subcategories': SubCategorySitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('referrals/', include('referrals.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('reviews/', include('reviews.urls')),
    path(
        'robots.txt', serve,
        {'path': 'robots.txt', 'document_root': settings.BASE_DIR}),
    path(
        'sitemap.xml', sitemap,
        {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

referrals/urls.py
from django.urls import path
from . import views

app_name = 'referrals'

urlpatterns = [
    path('dashboard/', views.referral_dashboard, name='dashboard'),
    path('redeem/', views.redeem_balance, name='redeem_balance'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <title>
        Supplemint - 
        {% block title_extension %}{% endblock %}
    </title>

    {% block meta %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock %}

    {% block extra_meta %}
    {% endblock %}

    {% block core_css %}
    {% load compress %}
    <!-- Preload critical CSS -->
    {% compress css %}
    <link rel="preload" href="{% static 'css/base.css' %}" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="{% static 'css/base.css' %}"></noscript>
    {% endcompress %}
    
    <!-- Load non-critical CSS asynchronously -->
    {% compress css %}
    <link rel="preload" href="{% static 'css/contact.css' %}" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="{% static 'css/contact.css' %}"></noscript>
    {% endcompress %}
    
    {% compress css %}
    <link rel="preload" href="{% static 'css/products.css' %}" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="{% static 'css/products.css' %}"></noscript>
    {% endcompress %}
    {% endblock %}

    {% block favicons %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    {% endblock %}

    {% block extra_css %}
    {% endblock %}

    {% block head %}
    {% endblock %}

    {% block core_js %}
    <!-- Load non-critical JS with defer -->
    <script src="https://kit.fontawesome.com/1d63fa792f.js" crossorigin="anonymous" defer></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous" defer></script>
    <script src="https://js.stripe.com/v3/" defer></script>
    {% endblock %}

</head>

<body>
    <header class="header-container">
        <div id="delivery-banner">
            <div>
                <h4>Free delivery on orders over €{{ free_delivery_threshold }}!</h4>
            </div>
        </div>
        <div class="header-row">
            <div class="logo-section">
                <a href="{% url 'home' %}" class="logo-link">
                    <h2 class="brand-name">Supplemint</h2>
                </a>
            </div>
            <div class="search-section">
                <form method="GET" action="{% url 'products' %}" class="search-form">
                    <input class="search-input" type="text" name="q" aria-label="search" placeholder="Search...">
                    <button class="search-button" aria-label="searchbutton" type="submit">
                        <i class="fas fa-search search-icon"></i>
                    </button>
                </form>
            </div>
            <div class="user-section">
                <ul class="user-menu">
                    <li class="user-item dropdown">
                        {% if request.user.is_authenticated %}
                        <a class="account-link" href="{% url 'profile' %}" id="account-menu">
                            <div class="account-info">
                                <div><i class="fas fa-user fa-lg"></i></div>
                                <span class="account-text">Account</span>
                            </div>
                        </a>
                        {% else %}
                        <div class="account-info" id="account-menu">
                            <div><i class="fas fa-user fa-lg"></i></div>
                            <span class="account-text">Account</span>
                        </div>

                        {% endif %}
                        <div class="dropdown-content" aria-labelledby="account-menu">
                            {% if request.user.is_authenticated %}
                            {% if request.user.is_superuser %}
                            <a href="{% url 'product_management' %}" class="dropdown-link">Product Management</a>
                            {% endif %}
                            <a href="{% url 'profile' %}" class="dropdown-link">My Profile</a>
                            <a href="{% url 'referrals:dashboard' %}" class="dropdown-link">Referral Dashboard</a>
                            <a href="{% url 'account_logout' %}" class="dropdown-link">Logout</a>
                            {% else %}
                            <a href="{% url 'account_signup' %}" class="dropdown-link">Register</a>
                            <a href="{% url 'account_login' %}" class="dropdown-link">Login</a>
                            {% endif %}
                        </div>
                    </li>
                    <li class="user-item">
                        <a class="{% if grand_total %}highlighted-link{% else %}normal-link{% endif %}"
                            href="{% url 'view_bag' %}">
                            <div class="cart-info">
                                <div><i class="fas fa-shopping-bag fa-lg"></i></div>
                                <p class="cart-text">
                                    {% if grand_total %}
                                    ${{ grand_total|floatformat:2 }}
                                    {% else %}
                                    $0.00
                                    {% endif %}
                                </p>
                            </div>
                        </a>
                    </li>
                    <li class="user-item">
                        <button class="nav-toggle" aria-label="Toggle navigation">
                            <i class="fas fa-bars"></i>
                        </button>
                    </li>
                </ul>
            </div>
        </div>
        <div class="nav-row">
            <nav>
                {% include 'includes/main-nav.html' %}
            </nav>
        </div>
    </header>

    {% if messages %}
    <div class="message-container">
        {% for message in messages %}
        {% with message.level as level %}
        {% if level == 40 %}
        {% include 'includes/toasts/toast_error.html' %}
        {% elif level == 30 %}
        {% include 'includes/toasts/toast_warning.html' %}
        {% elif level == 25 %}
        {% include 'includes/toasts/toast_success.html' %}
        {% else %}
        {% include 'includes/toasts/toast_info.html' %}
        {% endif %}
        {% endwith %}
        {% endfor %}
    </div>
    {% endif %}

    {% block page_header %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% include 'includes/footer.html' %}

    {% block postloadjs %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const toasts = document.querySelectorAll('.toast-container');

            toasts.forEach(toast => {
                setTimeout(() => {
                    toast.style.opacity = '0';
                    toast.style.transform = 'translateY(-20px)';
                    setTimeout(() => {
                        toast.style.display = 'none';
                    }, 300);
                }, 3000);
            });
        });
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const navToggle = document.querySelector('.nav-toggle');
            const mainNav = document.querySelector('.main-nav');

            navToggle.addEventListener('click', function () {
                mainNav.classList.toggle('active');
            });
        });
    </script>
    {% endblock %}

</body>

</html>